sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "5"
before_script:
  - npm prune
  - git config --global user.email "jonelson+lerna-sr-travis-ci@atlassian.com"
  - git config --global user.name "Joshua Nelson"
  - git remote rm origin
  - git remote add origin https://lerna-sr-travis-ci:${RELEASE_GH_TOKEN}@github.com/atlassian/lerna-semantic-release.git
  - git log
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
