sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "5"
before_script:
  - '[[ $TRAVIS_BRANCH == "master" ]] && ./bin/before.sh'
after_success:
  - '[[ $TRAVIS_BRANCH == "master" ]] && npm run semantic-release'
git:
  depth: 100
