sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "5"
before_script:
  - '[[ $TRAVIS_BRANCH == "caribou" ]] && { $TRAVIS_BUILD_DIR/bin/before.sh };'
after_success:
  - '[[ $TRAVIS_BRANCH == "caribou" ]] && { npm run semantic-release };'
git:
  depth: 100
