sudo: false
language: node_js
node_js:
  - "4"
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
