sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "5"
before_script: .travis/before_script.sh
after_success: .travis/after_success.sh
git:
  depth: 9999
