sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "5"
before_script:
  - npm prune
  - git config --global user.email "jonelson+lerna-sr-travis-ci@atlassian.com"
  - git config --global user.name "Joshua Nelson"
  - git config --global push.default simple
  - git remote rm origin
  - git remote add origin https://lerna-sr-travis-ci:${RELEASE_GH_TOKEN}@github.com/atlassian/lerna-semantic-release.git
  - git checkout $TRAVIS_BRANCH #Travis CI starts in a detached state, need to set up so we're on a branch that can push to the remote
  - git fetch
  - git branch -u origin/$TRAVIS_BRANCH
  - git log -E --format=%H==SPLIT==%B==END== 6e246a7f245f3da766cd43e07408d0266d6bc756..HEAD #debug
after_success:
  - npm run semantic-release
branches:
  only:
    - caribou
git:
  depth: 100
